### ISSUE TITLE
bug(`learnerd`): unintuitive error for missing retrievers

### ISSUE THREAD

**Issue by jtriley-eth** [Autoparallel/learner#139]
**Describe the bug**

If a user (me) doesn't read through the README to the configuration section, the lack of files in the `~/.learner/retriever/` directory causes the `add` command to fail with `LearnerError(InvalidIdentifier)`.

**To Reproduce**

1. `cargo add learnerd`
2. `learner init`
3. `learner add 2301.07041`

**Expected behavior**

"Bug" isn't the best description here, it's failing as it should. But there wasn't a clear signal indicating what exactly 

**Environment:**
 - OS: `Ubuntu xx.xx`
 - Rust Version: 
 - Crate Version: `0.3.3`

**Comment by Autoparallel** [comment]
Thanks for finding this and also submitting PR :)
